// react/demo/src/bootstrap/samples/slider/Accessibility.route.tsx
import type {SliderSlotLabelContext} from '@agnos-ui/react-bootstrap/components/slider';
import {Slider} from '@agnos-ui/react-bootstrap/components/slider';
import {useState} from 'react';

const AccessibilitySliderDemo = () => {
	const [sliderValues, setSliderValues] = useState([1733007600000, 1735599600000]);
	const stepSize = 86400000; // 1 day in milliseconds
	const min = 1733007600000; // 01-12-2024
	const max = 1735599600000; // 31-12-2024

	const ariaLabelledBy = () => 'labelID';
	const ariaValueText = (value: number, index: number) => {
		const dateString = new Date(value).toLocaleDateString('en-GB', {dateStyle: 'medium', timeZone: 'UTC'});
		if (index == 0) {
			return `Minimum date: ${dateString}`;
		} else {
			return `Maximum date: ${dateString}`;
		}
	};
	const label = ({value}: SliderSlotLabelContext) => new Date(value).toLocaleDateString('en-GB', {dateStyle: 'medium', timeZone: 'UTC'});

	return (
		<>
			<h2>Slider with custom accessibility labels</h2>
			<span id="labelID">Date range</span>
			<Slider
				min={min}
				max={max}
				stepSize={stepSize}
				values={sliderValues}
				ariaLabelledBy={ariaLabelledBy}
				ariaValueText={ariaValueText}
				label={label}
				onValuesChange={setSliderValues}
			/>
		</>
	);
};
export default AccessibilitySliderDemo;

// svelte/demo/src/bootstrap/samples/slider/Accessibility.route.svelte
<script lang="ts">
	import {Slider} from '@agnos-ui/svelte-bootstrap/components/slider';

	let sliderValues = $state([1733007600000, 1735599600000]);
	const stepSize = 86400000; // 1 day in milliseconds
	const min = 1733007600000; // 01-12-2024
	const max = 1735599600000; // 31-12-2024

	const ariaLabelledBy = () => 'labelID';
	const ariaValueText = (value: number, index: number) => {
		const dateString = new Date(value).toLocaleDateString('en-GB', {dateStyle: 'medium', timeZone: 'UTC'});
		if (index == 0) {
			return `Minimum date: ${dateString}`;
		} else {
			return `Maximum date: ${dateString}`;
		}
	};
</script>

<h2>Slider with custom accessibility labels</h2>
<span id="labelID">Date range</span>
<Slider {min} {max} {stepSize} {ariaLabelledBy} {ariaValueText} bind:values={sliderValues}>
	{#snippet label({value})}
		{new Date(value).toLocaleDateString('en-GB', {dateStyle: 'medium', timeZone: 'UTC'})}
	{/snippet}
</Slider>
