// svelte/bootstrap/src/components/drawer/Drawer.svelte
<script lang="ts">
	import {Slot} from '@agnos-ui/svelte-headless/slot';
	import {callWidgetFactory} from '../../config';
	import type {DrawerContext, DrawerProps} from './drawer.gen';
	import {createDrawer} from './drawer.gen';
	import DrawerDefaultStructure from './DrawerDefaultStructure.svelte';
	import type {DrawerApi} from 'core-bootstrap/dist';

	let {width = $bindable(), height = $bindable(), ...props}: Partial<DrawerProps> = $props();

	const widget = callWidgetFactory(createDrawer, {
		get props() {
			return {...props, width, height};
		},
		defaultConfig: {structure},
		events: {
			onWidthChange: (value: number) => {
				width = value;
			},
			onHeightChange: (value: number) => {
				height = value;
			},
		},
	});
	const {
		directives: {backdropDirective, backdropPortalDirective, drawerDirective, drawerPortalDirective, containerDirective},
		state,
	} = widget;

	export const api: DrawerApi = widget.api;
</script>

{#snippet structure(props: DrawerContext)}
	<DrawerDefaultStructure {...props} />
{/snippet}

{#if !state.hidden}
	<div use:drawerPortalDirective use:drawerDirective>
		<div use:containerDirective>
			<Slot content={state.structure} props={widget} />
		</div>
	</div>
{/if}
{#if !state.backdropHidden}
	<div use:backdropPortalDirective use:backdropDirective></div>
{/if}

// react/bootstrap/src/components/drawer/drawer.tsx
import {Slot} from '@agnos-ui/react-headless/slot';
import {useWidget} from '../../config';
import type {DrawerApi, DrawerContext, DrawerProps} from './drawer.gen';
import {createDrawer} from './drawer.gen';
import type {Ref} from 'react';
import {useImperativeHandle} from 'react';
import {useDirectives} from '@agnos-ui/react-headless/utils/directive';

const DrawerHeader = (slotContext: DrawerContext) => (
	<div className="au-drawer-header">
		<Slot slotContent={slotContext.state.header} props={slotContext} />
	</div>
);

/**
 * Renders the default slot structure for a Toast component.
 *
 * @param slotContext - The context containing the state and properties for the Toast component.
 * @returns The JSX element representing the default slot structure of the Toast.
 */
export const DefaultDrawerSlotStructure = (slotContext: DrawerContext) => (
	<div {...useDirectives(slotContext.directives.drawerPortalDirective, slotContext.directives.drawerDirective)}>
		<DrawerHeader {...slotContext} />
		<div className="au-drawer-body">
			<Slot slotContent={slotContext.state.children} props={slotContext} />
		</div>
		<div {...useDirectives(slotContext.directives.backdropPortalDirective, slotContext.directives.backdropDirective)} />
	</div>
);

const defaultConfig: Partial<DrawerProps> = {
	structure: DefaultDrawerSlotStructure,
};

/**
 * Drawer component that integrates with a widget context and renders a slot structure.
 *
 * @param props - The properties for the Drawer component.
 * @param props.ref - Ref to expose the Drawer API.
 * @returns The rendered Drawer component.
 *
 * The Drawer component uses the {@link useWidget} hook to create a widget context with the provided
 * configuration. It renders the slot content using the `Slot` component.
 */
export function Drawer(props: Partial<DrawerProps> & {ref?: Ref<DrawerApi>}) {
	const widgetContext = useWidget(createDrawer, props, {...defaultConfig});
	useImperativeHandle(props.ref, () => widgetContext.api, [widgetContext.api]);
	return <Slot slotContent={widgetContext.state.structure} props={widgetContext} />;
}
