// svelte/demo/src/bootstrap/samples/drawer/Basic.route.svelte
<script lang="ts">
	import {Drawer} from '@agnos-ui/svelte-bootstrap/components/drawer';

	type DrawerTypes = 'inline-start' | 'inline-end' | 'block-start' | 'block-end';
	let drawerPlacement = $state('inline-start' as DrawerTypes);
	// svelte-ignore non_reactive_update
	let drawer: Drawer;
	let mounted = $state(true);
	let width = $state(300);
	let height = $state(300);

	function toggleDrawer() {
		mounted = true;
		requestAnimationFrame(() => {
			drawer.api.open();
		});
	}
</script>

<button class="btn btn-primary mb-3" id="toggleDrawer" onclick={toggleDrawer}>Toggle drawer</button>
<div class="d-flex align-items-center">
	<label for="drawerPlacement" class="me-3">Placement:</label>
	<select id="drawerPlacement" bind:value={drawerPlacement} class="w-auto form-select">
		<option value="inline-start">Left</option>
		<option value="inline-end">Right</option>
		<option value="block-start">Top</option>
		<option value="block-end">Bottom</option>
	</select>
</div>

{#if mounted}
	<Drawer
		bind:this={drawer}
		className={drawerPlacement}
		header="Basic drawer"
		resizable
		onHidden={() => (mounted = false)}
		onHeightChange={(h) => (height = h)}
		{height}
		onWidthChange={(w) => (width = w)}
		{width}
	>
		<ul>
			<li>First item</li>
			<li>Second item</li>
			<li>Third item</li>
		</ul>
	</Drawer>
{/if}

// react/demo/src/bootstrap/samples/drawer/Basic.route.tsx
import type {DrawerApi} from '@agnos-ui/react-bootstrap/components/drawer';
import {Drawer} from '@agnos-ui/react-bootstrap/components/drawer';
import {useRef, useState} from 'react';

type DrawerTypes = 'inline-start' | 'inline-end' | 'block-start' | 'block-end';

const BasicDemo = () => {
	const [placement, setPosition] = useState<DrawerTypes>('inline-start');
	const refDrawer = useRef<DrawerApi>(null);
	const [mounted, setMounted] = useState(false);
	const [width, setWidth] = useState(200);
	const [height, setHeight] = useState(200);

	function toggle() {
		setMounted(true);
		requestAnimationFrame(() => requestAnimationFrame(() => refDrawer.current?.open()));
	}

	function onHidden() {
		setMounted(false);
	}

	return (
		<>
			<button className="btn btn-primary mb-3" id="toggleDrawer" onClick={toggle}>
				Toggle drawer
			</button>
			<div className="d-flex align-items-center">
				<label htmlFor="drawerPlacement" className="me-3">
					Placement:
				</label>
				<select id="drawerPlacement" className="w-auto form-select" onChange={(e) => setPosition(e.target.value as DrawerTypes)} value={placement}>
					<option value="inline-start">Left</option>
					<option value="inline-end">Right</option>
					<option value="block-start">Top</option>
					<option value="block-end">Bottom</option>
				</select>
			</div>
			{mounted && (
				<Drawer
					ref={refDrawer}
					className={placement}
					header={<>Hi, I am drawer!</>}
					resizable
					onHidden={onHidden}
					width={width}
					height={height}
					onHeightChange={setHeight}
					onWidthChange={setWidth}
				>
					<ul>
						<li>First item</li>
						<li>Second item</li>
						<li>Third item</li>
					</ul>
				</Drawer>
			)}
		</>
	);
};

export default BasicDemo;
