// svelte/demo/src/bootstrap/samples/drawer/Basic.route.svelte
<script lang="ts">
	import {Drawer} from '@agnos-ui/svelte-bootstrap/components/drawer';

	type DrawerTypes = 'inline-start' | 'inline-end' | 'block-start' | 'block-end';
	let drawerPlacement = $state('inline-start' as DrawerTypes);
	// svelte-ignore non_reactive_update
	let drawer: Drawer;
	let mounted = $state(true);
	let width = $state(300);
	let height = $state(300);

	function toggleDrawer() {
		mounted = true;
		requestAnimationFrame(() => {
			drawer.api.open();
		});
	}
</script>

<button class="btn btn-primary mb-3" id="toggleDrawer" onclick={toggleDrawer}>Toggle drawer</button>
<div class="d-flex align-items-center">
	<label for="drawerPlacement" class="me-3">Placement:</label>
	<select id="drawerPlacement" bind:value={drawerPlacement} class="w-auto form-select">
		<option value="inline-start">Left</option>
		<option value="inline-end">Right</option>
		<option value="block-start">Top</option>
		<option value="block-end">Bottom</option>
	</select>
</div>

{#if mounted}
	<Drawer
		bind:this={drawer}
		className={drawerPlacement}
		header="Basic drawer"
		resizable
		onHidden={() => (mounted = false)}
		onHeightChange={(h) => (height = h)}
		{height}
		onWidthChange={(w) => (width = w)}
		{width}
	>
		<ul>
			<li>First item</li>
			<li>Second item</li>
			<li>Third item</li>
		</ul>
	</Drawer>
{/if}

// angular/demo/bootstrap/src/app/samples/drawer/basic.route.ts
import type {DrawerPositions, DrawerWidget} from '@agnos-ui/angular-bootstrap';
import {DrawerComponent, DrawerHeaderDirective} from '@agnos-ui/angular-bootstrap';
import {Component, signal, viewChild} from '@angular/core';
import {FormsModule} from '@angular/forms';

@Component({
	template: `
		<button class="btn btn-primary mb-3" id="toggleDrawer" (click)="toggleDrawer()">Toggle drawer</button>
		<div class="d-flex align-items-center">
			<label for="drawerPlacement" class="me-3">Placement:</label>
			<select id="drawerPlacement" [ngModel]="drawerPlacement()" (ngModelChange)="drawerPlacement.set($event)" class="w-auto form-select">
				<option value="inline-start">Left</option>
				<option value="inline-end">Right</option>
				<option value="block-start">Top</option>
				<option value="block-end">Bottom</option>
			</select>
		</div>
		@if (mounted()) {
			<au-component #drawer auDrawer [auClassName]="drawerPlacement()" (auHidden)="onHidden()" [(auWidth)]="width" [(auHeight)]="height" auResizable>
				<ng-template auDrawerHeader> Hi, I am drawer! </ng-template>
				<ul>
					<li>First item</li>
					<li>Second item</li>
					<li>Third item</li>
				</ul>
			</au-component>
		}
	`,
	imports: [DrawerComponent, FormsModule, DrawerHeaderDirective],
})
export default class BasicDrawerComponent {
	readonly drawerPlacement = signal<DrawerPositions>('inline-start');
	readonly drawer = viewChild<DrawerWidget>('drawer');
	readonly mounted = signal(true);
	readonly width = signal(200);
	readonly height = signal(200);

	onHidden() {
		this.mounted.set(false);
	}

	toggleDrawer() {
		this.mounted.set(true);
		requestAnimationFrame(() => this.drawer()?.api.open());
	}
}
